<?php

namespace AdminBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * ModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'appModuleObj' => array('label' => 'App Module', 'type' => 'object', 'acl' => 'edit',
                'typeDetail' => array(
                    'table' => 'app_module', 'field' => 'id', 'bundle' => 'sysadmin', 'type' => 'none',
                    'choices' => array(
                        'autoRefresh' => true, 'selfReference' => false
                    )
                ),
                'form' => array('type' => 'radio')
            ),
            // Used to determines the parent in tree view (app_module.appModuleObj)
            'appParentModuleObj' => array('field' => 'appModuleObj', 'table' => 'app_module', 'label' => 'Parent Module',
                'type' => 'object', 'acl' => 'read', 'dependency' => 'appModuleObj', 'typeDetail' =>
                    array(
                        'table' => 'app_module', 'tableAlias' => 'appParentModule',
                        'field' => 'id', 'bundle' => 'sysadmin', 'type' => 'none'
                    )
            ),
            'name' => array('label' => 'Name', 'type' => 'text', 'acl' => 'edit'),
            'description' => array('label' => 'Description', 'type' => 'text', 'acl' => 'read', 'table' => 'app_module', 'dependency' => 'appModuleObj'),
            'priority' => array('label' => 'Priority', 'type' => 'number', 'acl' => 'edit'),

            // Foreign fields, used to get the icon of the module
            'appIconObj' => array('table' => 'app_module', 'label' => 'Icon', 'type' => 'object', 'acl' => 'read',
                'dependency' => 'appModuleObj', 'typeDetail' => array(
                    'table' => 'app_icon', 'bundle' => 'sysadmin', 'type' => 'none')),
            'icon' => array('table' => 'app_icon', 'field' => 'icon', 'label' => 'Icon', 'type' => 'icon',
                'acl' => 'read', 'dependency' => 'appIconObj'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read'),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read'),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true)
        ));
    }
}
