<?php

namespace AccountingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * ClientCurrentAccountStoreInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientCurrentAccountStoreInfoRepository extends BaseCurrentAccountStoreInfoRepository
{
    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::processMetadata(array(
            'clientCurrentAccountObj' => array('label' => 'Client Current Account', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'clientCurrentAccount', 'bundle' => 'accounting', 'type' => 'select'))
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}