<?php

namespace AccountingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * ClientDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientDocumentRepositorysssss extends BaseDocumentRepository
{
    static protected $metadata = null;

    /**
     * Defines parent method
     * @return string
     */
    protected function getContext()
    {
        return 'client';
    }

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::processMetadata(array(
            'clientDocumentTypeObj' => array('label' => 'Document Type', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'clientDocumentType', 'bundle' => 'accounting', 'type' => 'select')),
            'clientObj' => array('label' => 'Client', 'type' => 'object', 'acl' => 'edit',
                'typeDetail' => array(
                    'table' => 'client', 'fieldInView' => 'client_name', 'bundle' => 'entities', 'type' => 'none'),
                'form' => array('type' => 'auto-complete')
            ),
            'storeInfoObjArr' => array('label' => 'Store Info', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'clientDocumentStoreInfo', 'bundle' => 'accounting', 'type' => 'array'),
                'form' => array('type' => 'array')
            )
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}