<?php

namespace Bck\SysadminBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;
use AppBundle\Service\HelperService;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $langPrefix = HelperService::getGlobalVar('langPrefix');
        $name_lang = 'name_'.$langPrefix;

        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'alpha2Code' => array('label' => 'Alpha2 Code', 'type' => 'text', 'acl' => 'edit'),
            'alpha3Code' => array('label' => 'Alpha3 Code', 'type' => 'text', 'acl' => 'edit'),
            'name_pt' => array('label' => 'Name PT', 'type' => 'text', 'acl' => 'edit'),
            'name_es' => array('label' => 'Name ES', 'type' => 'text', 'acl' => 'edit'),
            'name_en' => array('label' => 'Name EN', 'type' => 'text', 'acl' => 'edit'),
            'name' => array('label' => 'Name', 'field' => $name_lang, 'type' => 'text', 'acl' => 'read',
                'form' => array('type' => 'none'),
                'normalizer' => array('method' => 'getName')
            ),
            'appIconObj' => array('label' => 'Icon', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'app_icon', 'fieldInView' => 'icon', 'bundlePrefix' => 'bck', 'bundle' => 'sysadmin', 'type' => 'none',
                'choices' => array('query' => 'getChoicesForLink')), 'isRequired' => false,
                'form' => array('type' => 'html-select')
            ),
            'icon' => array('table' => 'app_icon', 'field' => 'icon', 'label' => 'Icon', 'type' => 'icon',
                'acl' => 'read', 'dependency' => 'appIconObj', 'form' => array('type' => 'none')),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}