<?php

namespace Bck\SysadminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DbErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DbErrorRepository extends EntityRepository
{
}
