<?php

namespace Bck\SysadminBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * ModuleMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleMenuRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'appModuleObj' => array('label' => 'Module', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'app_module', 'bundlePrefix' => 'bck', 'bundle' => 'sysadmin', 'field' => 'id', 'type' => 'none')),
            'name' => array('label' => 'Name', 'type' => 'text', 'acl' => 'edit'),
            'description' => array('label' => 'Description', 'type' => 'text', 'acl' => 'edit'),
            'route' => array('label' => 'Route', 'type' => 'text', 'acl' => 'edit'),
            'priority' => array('label' => 'Priority', 'type' => 'number', 'acl' => 'edit'),
            'requiresAdminRole' => array('label' => 'Requires Admin Role', 'type' => 'boolean', 'acl' => 'edit'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }

    /**
     * Get all objects joined with icon
     * @param $options (array with queryBuilder options format)
     * @return mixed
     */
    public function getAllJoinWithIcon($options)
    {
        $qb = $this->queryBuilder($options, false);

        // Join with module
        if (in_array("appModuleObj", $options['fields'])) {
            // Join with App Icon (to get module icon)
            $qb->leftJoin('Bck\SysadminBundle\Entity\Icon',
                'app_icon',
                'WITH',
                ('app_icon.id = app_module.appIconObj')
            );
        }

        return $this->executeQueryBuilder($qb);
    }
}