<?php

namespace Bck\SysadminBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * SystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'name' => array('label' => 'Name', 'type' => 'text', 'acl' => 'edit'),
            'dbHost' => array('label' => 'Db Host', 'type' => 'text', 'acl' => 'edit'),
            'dbName' => array('label' => 'Db Name', 'type' => 'text', 'acl' => 'edit'),
            'dbUsername' => array('label' => 'Db Username', 'type' => 'text', 'acl' => 'edit'),
            'dbPassword' => array('label' => 'Db Password', 'type' => 'none', 'acl' => 'edit', 'form' => array(
                'type' => 'password'
            )),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }

    /**
     * Find system by primary key (id) with fallback to find by name
     * @param $system
     * @return mixed
     */
    public function findOneByLogin($system)
    {
        $systemObj = $this->find($system);

        if(!$systemObj) {
            $systemObj = $this->findOneByName($system);
        }

        return $systemObj;
    }
}