<?php

namespace LoginBundle\Entity;

use AdminBundle\Entity\UserRepository as BaseUserRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends BaseUserRepository
{
    /**
     * @param $username
     * @return mixed
     */
    public function loadUserByUsername($username)
    {
        $qb = $this->queryBuilder(
            array(
                'criteria' => array(
                    array('field' => 'username', 'expr' => 'eq', 'value' => $username),
                    // Not necessary, the clause bellow filters empty and also null values!
                    //array('field' => 'password', 'expr' => 'isNotNull', 'value' => null),
                    array('field' => 'password', 'expr' => 'neq', 'value' => '')
                )
            ),
            false
        );
        return $this->executeQueryBuilder($qb, 'getOneOrNullResult');
    }
}