<?php

namespace Bck\BookingBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * BookingPaxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingPaxRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'bookingObj' => array('label' => '', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'booking', 'bundlePrefix' => 'bck', 'bundle' => 'booking', 'type' => 'none')),
            'title' => array('label' => 'Title', 'type' => 'enum', 'acl' => 'edit', 'isDefault' => true,
                'typeDetail' => array(
                    'type' => 'text', 'choices' => array(
                        'value' => array(
                            'Mr.' => 'Mr.', 'Ms.' => 'Ms.'
                        )
                    )),
                'form' => array('type' => 'select')
            ),
            'name' => array('label' => 'Name', 'type' => 'text', 'acl' => 'edit', 'isDefault' => true),
            'surname' => array('label' => 'Surname', 'type' => 'text', 'acl' => 'edit', 'isDefault' => true),
            'birthDate' => array('label' => 'Birth Date', 'type' => 'date', 'acl' => 'edit', 'isRequired' => false, 'isDefault' => true),
            // @TODO Change label according with country ('DNI/NIE/Passport', ext.)
            'identification' => array('label' => 'Identification / Passport', 'type' => 'text', 'acl' => 'edit', 'isDefault' => true),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}