<?php

namespace AccountingBundle\Entity;

/**
 * ClientDocumentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientDocumentTypeRepository extends BaseDocumentTypeRepository
{}