<?php

namespace AccountingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * ClientDocumentInvoiceDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientDocumentInvoiceDetailRepository extends BaseDocumentInvoiceDetailRepository
{
    static protected $metadata = null;

    /**
     * Defines parent method
     * @return string
     */
    protected function getContext()
    {
        return 'client';
    }

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::processMetadata(array(
            'clientDocumentObj' => array('label' => '', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array('table' => 'clientDocument', 'bundle' => 'accounting', 'type' => 'none')),
            // Foreign fields (this fields are mandatory for search in add document invoice rectification (tree-view))
            'clientDocument_code' => array('label' => 'Code', 'table' => '',
                'field' => 'CONCAT(clientDocument.codePrefix, clientDocument.codeNumber)',
                'dependency' => 'clientDocumentObj', 'type' => 'code', 'acl' => 'read',
                'normalizer' => array('method' => 'getCode')
            ),
            'clientDocument_date' => array('table' => 'clientDocument', 'field' => 'date', 'label' => 'Date',
                'type' => 'date', 'acl' => 'read', 'dependency' => 'clientDocumentObj',
                'form' => array('type' => 'none')
            ),
            'clientDocument_dueDate' => array('table' => 'clientDocument', 'field' => 'dueDate', 'label' => 'Due Date',
                'type' => 'date', 'acl' => 'read', 'dependency' => 'clientDocumentObj',
                'form' => array('type' => 'none')
            ),
            'clientDocumentTypeObj' => array('table' => 'clientDocument', 'field' => 'clientDocumentTypeObj',
                'label' => 'Document Type', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array('table' => 'clientDocumentType',
                    'bundle' => 'accounting', 'type' => 'none'),
                'dependency' => 'clientDocumentObj'
            ),
            'clientDocumentType_name' => array('table' => 'clientDocumentType', 'field' => 'name',
                'label' => 'Doc. Name',
                'type' => 'text', 'acl' => 'read', 'dependency' => 'clientDocumentTypeObj'
            ),
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}