<?php

namespace AccountingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * EntityCurrentAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityCurrentAccountRepository extends BaseCurrentAccountRepository
{
    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::processMetadata(array(
            'entityDocumentTypeObj' => array('label' => 'Document Type', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'entityDocumentType', 'bundle' => 'accounting', 'type' => 'select')),
            'entityObj' => array('label' => 'Entity', 'type' => 'object', 'acl' => 'edit',
                'typeDetail' => array(
                    'table' => 'entity', 'fieldInView' => 'entity_name', 'bundle' => 'entities', 'type' => 'none'),
                'form' => array('type' => 'auto-complete')
            )
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}