<?php

namespace AccountingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * SupplierDocumentInvoiceRectificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierDocumentInvoiceRectificationRepository extends BaseDocumentInvoiceRectificationRepository
{
    static protected $metadata = null;

    /**
     * Defines parent method
     * @return string
     */
    protected function getLocalEntityContext()
    {
        return 'supplier';
    }

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            'supplierDocumentInvoiceDetailObj' => array('label' => '', 'type' => 'object',
                'acl' => 'read', 'typeDetail' => array(
                    'table' => 'supplierDocumentInvoiceDetail', 'field' => 'id', 'bundle' => 'accounting', 'type' => 'none',
                    'metadata' => array('method' => 'merge', 'pushAfterField' => 'serviceObj')
                ),
                'form' => array('type' => 'embed', 'typeClass' => 'SupplierDocumentInvoiceDetailNoService')
            ),
            'rectificationSupplierDocumentInvoiceDetailObj' => array('label' => '', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'supplierDocumentInvoiceDetail', 'tableAlias' => 'rectificationSupplierDocumentInvoiceDetail',
                    'bundle' => 'accounting', 'type' => 'none'
                )
            ),
            // Foreign fields (is not used the entity type prefix (supplier),
            // to make fields compatibles with all entity types (supplier, entity, etc.), except in "Obj" fields)
            'rectificationSupplierDocumentObj' => array('table' => 'rectificationSupplierDocumentInvoiceDetail', 'field' => 'supplierDocumentObj',
                'label' => 'Document', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'supplierDocument', 'tableAlias' => 'rectificationSupplierDocument', 'bundle' => 'accounting', 'type' => 'none'),
                'dependency' => 'rectificationSupplierDocumentInvoiceDetailObj'
            ),
            'originalDocument_code' => array('label' => 'Original Doc.', 'table' => '',
                'field' => 'CONCAT(rectificationSupplierDocument.codePrefix, rectificationSupplierDocument.codeNumber)',
                'dependency' => 'rectificationSupplierDocumentObj', 'type' => 'code', 'acl' => 'read',
                'normalizer' => array('method' => 'getCode')
            ),
            'originalDocument_date' => array('table' => 'rectificationSupplierDocument', 'field' => 'date', 'label' => 'Date',
                'type' => 'date', 'acl' => 'read', 'dependency' => 'rectificationSupplierDocumentObj',
                'form' => array('type' => 'none')
            ),
            'originalDocument_dueDate' => array('table' => 'rectificationSupplierDocument', 'field' => 'dueDate', 'label' => 'Due Date',
                'type' => 'date', 'acl' => 'read', 'dependency' => 'rectificationSupplierDocumentObj',
                'form' => array('type' => 'none')
            ),
            'rectificationSupplierDocumentTypeObj' => array('table' => 'rectificationSupplierDocument', 'field' => 'supplierDocumentTypeObj',
                'label' => 'Document Type', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array('table' => 'supplierDocumentType', 'tableAlias' => 'rectificationSupplierDocumentType',
                    'bundle' => 'accounting', 'type' => 'none'),
                'dependency' => 'rectificationSupplierDocumentObj'
            ),
            'originalDocumentType_name' => array('table' => 'rectificationSupplierDocumentType', 'field' => 'name',
                'label' => 'Doc. Name',
                'type' => 'text', 'acl' => 'read', 'dependency' => 'rectificationSupplierDocumentTypeObj'
            ),
            // Override fields when merge with DocumentInvoiceDetail
            // (service can't be edit, is inherited from original document)
            'serviceObj' => array('table' => 'supplierDocumentInvoiceDetail', 'label' => 'Service',
                'type' => 'object', 'acl' => 'read', 'dependency' => 'supplierDocumentInvoiceDetailObj',
                'typeDetail' => array(
                    'table' => 'service', 'bundle' => 'services', 'type' => 'none'
                )
            ),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));

        return self::$metadata = HelperService::pushIntoArray($localMetadata, $parentMetadata);
    }
}