<?php

namespace Frt\CommonBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * FrtHashResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrtHashResourceRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'clientObj' => array('label' => 'Client', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'client', 'bundlePrefix' => 'bck', 'bundle' => 'entities', 'type' => 'none')),
            'actionId' => array('label' => 'Action Id', 'type' => 'text', 'acl' => 'read', 'isDefault' => true),
            'actionParam' => array('label' => 'Action Param', 'type' => 'text', 'acl' => 'read', 'isDefault' => true),
            'hash' => array('label' => 'Hash', 'type' => 'text', 'acl' => 'read'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}