frt_services:
    resource: "@FrtServicesBundle/Controller/"
    type:     annotation

frt_booking:
    resource: "@FrtBookingBundle/Controller/"
    type:     annotation

frt_entities:
    resource: "@FrtEntitiesBundle/Controller/"
    type:     annotation

_frt_common:
    resource: "@FrtCommonBundle/Controller/"
    type:     annotation

_frt_accounting:
    resource: "@FrtAccountingBundle/Controller/"
    type:     annotation

_bck_management:
    resource: "@BckManagementBundle/Controller/"
    type:     annotation

_bck_common:
    resource: "@BckCommonBundle/Controller/"
    type:     annotation

_bck_settings:
    resource: "@BckSettingsBundle/Controller/"
    type:     annotation

_bck_user:
    resource: "@BckUserBundle/Controller/"
    type:     annotation

_bck_booking:
    resource: "@BckBookingBundle/Controller/"
    type:     annotation

_bck_accounting:
    resource: "@BckAccountingBundle/Controller/"
    type:     annotation

_bck_services:
    resource: "@BckServicesBundle/Controller/"
    type:     annotation

_bck_sysadmin:
    resource: "@BckSysadminBundle/Controller/"
    type:     annotation

_bck_admin:
    resource: "@BckAdminBundle/Controller/"
    type:     annotation

_login:
    resource: "@LoginBundle/Controller/"
    type:     annotation

_bck_home:
    resource: "@BckHomeBundle/Controller/"
    type:     annotation

_app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_bck_entities:
    resource: "@BckEntitiesBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"