# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AdminBundle\Entity\User:
            algorithm: bcrypt
            cost:      13

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_provider:
            id: login.service.user_provider

    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER
        ROLE_SYSADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~

            # activate different ways to authenticate

            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                login_path: /login
                check_path: /login/check
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
                always_use_default_target_path: true
            provider: database_provider
            logout:
                path: /logout
                target: /login

    # Note: The path is the route
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/assets/login, roles: IS_AUTHENTICATED_ANONYMOUSLY } # To access login assets
        - { path: ^/assets/vendor, roles: IS_AUTHENTICATED_ANONYMOUSLY } # To access fonts
        - { path: ^/sysadmin, roles: ROLE_SYSADMIN }
        # - { path: ^/admin, roles: ROLE_ADMIN } # Not used because user can access some admin menus
        - { path: ^/admin/module, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }