<?php

namespace Application\DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170321155934 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE bookingFile DROP FOREIGN KEY FK_47A3B9031023D0F2');
        $this->addSql('ALTER TABLE bookingObservation DROP FOREIGN KEY FK_B93BC73E1023D0F2');
        $this->addSql('ALTER TABLE bookingPax DROP FOREIGN KEY FK_D4B48D1A1023D0F2');
        $this->addSql('ALTER TABLE bookingService DROP FOREIGN KEY FK_6C897F331023D0F2');
        $this->addSql('ALTER TABLE travelBooking DROP FOREIGN KEY FK_F42889FF1023D0F2');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE24DA4789');
        $this->addSql('ALTER TABLE serviceBooking DROP FOREIGN KEY FK_E84536F724DA4789');
        $this->addSql('ALTER TABLE bookingServicePrice DROP FOREIGN KEY FK_F9787BE5198796DA');
        $this->addSql('ALTER TABLE bookingTravelService DROP FOREIGN KEY FK_FE033660198796DA');
        $this->addSql('CREATE TABLE travelBookingFile (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', name VARCHAR(128) NOT NULL COMMENT \'Name of file for user\', path VARCHAR(256) NOT NULL COMMENT \'File path\', extension VARCHAR(8) NOT NULL COMMENT \'Extension of file\', size INT UNSIGNED NOT NULL COMMENT \'Web file path\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_travelBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_FBC1277FBF396750 (id), INDEX IDX_FBC1277F9062FC3D (fk_travelBooking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serviceBookingFile (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', name VARCHAR(128) NOT NULL COMMENT \'Name of file for user\', path VARCHAR(256) NOT NULL COMMENT \'File path\', extension VARCHAR(8) NOT NULL COMMENT \'Extension of file\', size INT UNSIGNED NOT NULL COMMENT \'Web file path\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_serviceBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_3425FF18BF396750 (id), INDEX IDX_3425FF189D4BDF1E (fk_serviceBooking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE travelBookingObservation (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', name VARCHAR(128) NOT NULL COMMENT \'Name/title of observation\', description VARCHAR(526) DEFAULT NULL COMMENT \'Observation description\', type VARCHAR(16) DEFAULT NULL COMMENT \'Type of observation\', priority SMALLINT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'Priority for menu. Determines the order in the menus list\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_travelBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_1C9DF5DBF396750 (id), INDEX IDX_1C9DF5D9062FC3D (fk_travelBooking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serviceBookingObservation (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', name VARCHAR(128) NOT NULL COMMENT \'Name/title of observation\', description VARCHAR(526) DEFAULT NULL COMMENT \'Observation description\', type VARCHAR(16) DEFAULT NULL COMMENT \'Type of observation\', priority SMALLINT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'Priority for menu. Determines the order in the menus list\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_serviceBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_42CFAC3BBF396750 (id), INDEX IDX_42CFAC3B9D4BDF1E (fk_serviceBooking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE travelBookingPax (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', title VARCHAR(4) NOT NULL COMMENT \'Title\', name VARCHAR(64) NOT NULL COMMENT \'Name\', surname VARCHAR(64) NOT NULL COMMENT \'Surname\', birthDate DATE DEFAULT NULL COMMENT \'Birth date\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_travelBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_D0A9EBABBF396750 (id), INDEX IDX_D0A9EBAB9062FC3D (fk_travelBooking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serviceBookingPax (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', title VARCHAR(4) NOT NULL COMMENT \'Title\', name VARCHAR(64) NOT NULL COMMENT \'Name\', surname VARCHAR(64) NOT NULL COMMENT \'Surname\', birthDate DATE DEFAULT NULL COMMENT \'Birth date\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_serviceBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_8EE4159DBF396750 (id), INDEX IDX_8EE4159D9D4BDF1E (fk_serviceBooking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE travelBookingService (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_place INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', fk_service INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_supplier INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', reference VARCHAR(32) DEFAULT NULL COMMENT \'Any reference\', description VARCHAR(256) NOT NULL COMMENT \'Description\', startDate DATE NOT NULL COMMENT \'Start date of validation\', endDate DATE NOT NULL COMMENT \'End date of validation\', quantity SMALLINT UNSIGNED NOT NULL COMMENT \'Quantity\', isAutoAllot TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Enables auto allot management\', isAutoAvailability TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Enables auto availability management\', confirmationStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COMMENT \'Confirmation status\', invoiceStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COMMENT \'Invoice status\', totalCost NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total cost value\', totalMargin NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total profit\', totalSell NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total sell value\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_travelBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_placeTo INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_7D1C495BBF396750 (id), INDEX IDX_7D1C495B9062FC3D (fk_travelBooking), INDEX IDX_7D1C495BB5F070B8 (fk_place), INDEX IDX_7D1C495B3E1A161A (fk_placeTo), INDEX IDX_7D1C495B11B2A7FE (fk_service), INDEX IDX_7D1C495BA9022FA0 (fk_supplier), INDEX idx_travelBookingService_date (startDate, endDate), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serviceBookingService (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_service INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_supplier INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', reference VARCHAR(32) DEFAULT NULL COMMENT \'Any reference\', description VARCHAR(256) NOT NULL COMMENT \'Description\', startDate DATE NOT NULL COMMENT \'Start date of validation\', endDate DATE NOT NULL COMMENT \'End date of validation\', quantity SMALLINT UNSIGNED NOT NULL COMMENT \'Quantity\', isAutoAllot TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Enables auto allot management\', isAutoAvailability TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Enables auto availability management\', confirmationStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COMMENT \'Confirmation status\', invoiceStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COMMENT \'Invoice status\', totalCost NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total cost value\', totalMargin NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total profit\', totalSell NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total sell value\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_serviceBooking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_DE02FD47BF396750 (id), INDEX IDX_DE02FD479D4BDF1E (fk_serviceBooking), INDEX IDX_DE02FD4711B2A7FE (fk_service), INDEX IDX_DE02FD47A9022FA0 (fk_supplier), INDEX idx_serviceBookingService_date (startDate, endDate), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE travelBookingServicePrice (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', description VARCHAR(256) DEFAULT NULL COMMENT \'Description\', postingType VARCHAR(8) NOT NULL COMMENT \'Type of posting\', costValue NUMERIC(10, 4) DEFAULT \'0\' NOT NULL COMMENT \'Cost value\', marginMethod VARCHAR(8) DEFAULT NULL COMMENT \'Method to use to determinate the value\', marginValue NUMERIC(10, 4) DEFAULT \'0\' COMMENT \'Margin value\', sellValue NUMERIC(10, 4) DEFAULT \'0\' NOT NULL COMMENT \'Sell value\', userFieldTyped VARCHAR(6) NOT NULL COMMENT \'Field typed by user (COST or SELL)\', quantity SMALLINT UNSIGNED NOT NULL COMMENT \'Quantity\', totalCost NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total cost value\', totalMargin NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total profit\', totalSell NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total sell value\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_travelBookingService INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_2D7BB91FBF396750 (id), INDEX IDX_2D7BB91FDB767B37 (fk_travelBookingService), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE serviceBookingServicePrice (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', description VARCHAR(256) DEFAULT NULL COMMENT \'Description\', postingType VARCHAR(8) NOT NULL COMMENT \'Type of posting\', costValue NUMERIC(10, 4) DEFAULT \'0\' NOT NULL COMMENT \'Cost value\', marginMethod VARCHAR(8) DEFAULT NULL COMMENT \'Method to use to determinate the value\', marginValue NUMERIC(10, 4) DEFAULT \'0\' COMMENT \'Margin value\', sellValue NUMERIC(10, 4) DEFAULT \'0\' NOT NULL COMMENT \'Sell value\', userFieldTyped VARCHAR(6) NOT NULL COMMENT \'Field typed by user (COST or SELL)\', quantity SMALLINT UNSIGNED NOT NULL COMMENT \'Quantity\', totalCost NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total cost value\', totalMargin NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total profit\', totalSell NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total sell value\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_serviceBookingService INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_89E97B01BF396750 (id), INDEX IDX_89E97B019AA0BA06 (fk_serviceBookingService), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE travelBookingFile ADD CONSTRAINT FK_FBC1277F9062FC3D FOREIGN KEY (fk_travelBooking) REFERENCES travelBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serviceBookingFile ADD CONSTRAINT FK_3425FF189D4BDF1E FOREIGN KEY (fk_serviceBooking) REFERENCES serviceBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE travelBookingObservation ADD CONSTRAINT FK_1C9DF5D9062FC3D FOREIGN KEY (fk_travelBooking) REFERENCES travelBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serviceBookingObservation ADD CONSTRAINT FK_42CFAC3B9D4BDF1E FOREIGN KEY (fk_serviceBooking) REFERENCES serviceBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE travelBookingPax ADD CONSTRAINT FK_D0A9EBAB9062FC3D FOREIGN KEY (fk_travelBooking) REFERENCES travelBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serviceBookingPax ADD CONSTRAINT FK_8EE4159D9D4BDF1E FOREIGN KEY (fk_serviceBooking) REFERENCES serviceBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE travelBookingService ADD CONSTRAINT FK_7D1C495B9062FC3D FOREIGN KEY (fk_travelBooking) REFERENCES travelBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE travelBookingService ADD CONSTRAINT FK_7D1C495BB5F070B8 FOREIGN KEY (fk_place) REFERENCES place (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE travelBookingService ADD CONSTRAINT FK_7D1C495B3E1A161A FOREIGN KEY (fk_placeTo) REFERENCES place (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE travelBookingService ADD CONSTRAINT FK_7D1C495B11B2A7FE FOREIGN KEY (fk_service) REFERENCES service (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE travelBookingService ADD CONSTRAINT FK_7D1C495BA9022FA0 FOREIGN KEY (fk_supplier) REFERENCES supplier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE serviceBookingService ADD CONSTRAINT FK_DE02FD479D4BDF1E FOREIGN KEY (fk_serviceBooking) REFERENCES serviceBooking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serviceBookingService ADD CONSTRAINT FK_DE02FD4711B2A7FE FOREIGN KEY (fk_service) REFERENCES service (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE serviceBookingService ADD CONSTRAINT FK_DE02FD47A9022FA0 FOREIGN KEY (fk_supplier) REFERENCES supplier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE travelBookingServicePrice ADD CONSTRAINT FK_2D7BB91FDB767B37 FOREIGN KEY (fk_travelBookingService) REFERENCES travelBookingService (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE serviceBookingServicePrice ADD CONSTRAINT FK_89E97B019AA0BA06 FOREIGN KEY (fk_serviceBookingService) REFERENCES serviceBookingService (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE booking');
        $this->addSql('DROP TABLE bookingFile');
        $this->addSql('DROP TABLE bookingObservation');
        $this->addSql('DROP TABLE bookingPax');
        $this->addSql('DROP TABLE bookingService');
        $this->addSql('DROP TABLE bookingServicePrice');
        $this->addSql('DROP TABLE bookingTravelService');
        $this->addSql('DROP INDEX UNIQ_F42889FF1023D0F2 ON travelBooking');
        $this->addSql('ALTER TABLE travelBooking ADD fk_user INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', ADD fk_client INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', ADD startDate DATE DEFAULT NULL COMMENT \'Start date of booking\', ADD endDate DATE DEFAULT NULL COMMENT \'End date of booking\', ADD invoiceStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COMMENT \'Invoice status\', ADD confirmationStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COMMENT \'Confirmation status\', ADD totalCost NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total cost value\', ADD totalMargin NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total margin\', ADD totalMarkup NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total markup\', ADD totalProfit NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total profit\', ADD totalSell NUMERIC(10, 2) DEFAULT \'0\' NOT NULL COMMENT \'Total sell value\', ADD fk_travelBookingPax INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', CHANGE fk_booking fk_store INT UNSIGNED NOT NULL COMMENT \'Column row identifier\'');
        $this->addSql('ALTER TABLE travelBooking ADD CONSTRAINT FK_F42889FF86C38CDC FOREIGN KEY (fk_travelBookingPax) REFERENCES travelBookingPax (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE travelBooking ADD CONSTRAINT FK_F42889FF3EBA7B02 FOREIGN KEY (fk_store) REFERENCES store (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE travelBooking ADD CONSTRAINT FK_F42889FF1AD0877 FOREIGN KEY (fk_user) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE travelBooking ADD CONSTRAINT FK_F42889FFE7EA6CC5 FOREIGN KEY (fk_client) REFERENCES client (id) ON DELETE RESTRICT');
        $this->addSql('CREATE INDEX IDX_F42889FF86C38CDC ON travelBooking (fk_travelBookingPax)');
        $this->addSql('CREATE INDEX IDX_F42889FF3EBA7B02 ON travelBooking (fk_store)');
        $this->addSql('CREATE INDEX IDX_F42889FF1AD0877 ON travelBooking (fk_user)');
        $this->addSql('CREATE INDEX IDX_F42889FFE7EA6CC5 ON travelBooking (fk_client)');
        $this->addSql('DROP INDEX IDX_E84536F724DA4789 ON serviceBooking');
        $this->addSql('ALTER TABLE serviceBooking CHANGE fk_bookingpax fk_serviceBookingPax INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\'');
        $this->addSql('ALTER TABLE serviceBooking ADD CONSTRAINT FK_E84536F740D39B65 FOREIGN KEY (fk_serviceBookingPax) REFERENCES serviceBookingPax (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_E84536F740D39B65 ON serviceBooking (fk_serviceBookingPax)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE travelBooking DROP FOREIGN KEY FK_F42889FF86C38CDC');
        $this->addSql('ALTER TABLE serviceBooking DROP FOREIGN KEY FK_E84536F740D39B65');
        $this->addSql('ALTER TABLE travelBookingServicePrice DROP FOREIGN KEY FK_2D7BB91FDB767B37');
        $this->addSql('ALTER TABLE serviceBookingServicePrice DROP FOREIGN KEY FK_89E97B019AA0BA06');
        $this->addSql('CREATE TABLE booking (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_user INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', fk_store INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_client INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', totalCost NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total cost value\', totalSell NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total sell value\', startDate DATE DEFAULT NULL COMMENT \'Start date of booking\', endDate DATE DEFAULT NULL COMMENT \'End date of booking\', confirmationStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COLLATE utf8_unicode_ci COMMENT \'Confirmation status\', invoiceStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COLLATE utf8_unicode_ci COMMENT \'Invoice status\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_bookingPax INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', totalMargin NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total profit\', UNIQUE INDEX UNIQ_E00CEDDEBF396750 (id), INDEX IDX_E00CEDDE3EBA7B02 (fk_store), INDEX IDX_E00CEDDE1AD0877 (fk_user), INDEX IDX_E00CEDDEE7EA6CC5 (fk_client), INDEX IDX_E00CEDDE24DA4789 (fk_bookingPax), INDEX idx_booking_date (startDate, endDate), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookingFile (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_booking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', name VARCHAR(128) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Name of file for user\', path VARCHAR(256) NOT NULL COLLATE utf8_unicode_ci COMMENT \'File path\', extension VARCHAR(8) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Extension of file\', size INT UNSIGNED NOT NULL COMMENT \'Web file path\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', UNIQUE INDEX UNIQ_47A3B903BF396750 (id), INDEX IDX_47A3B9031023D0F2 (fk_booking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookingObservation (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_booking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', name VARCHAR(128) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Name/title of observation\', description VARCHAR(526) DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'Observation description\', type VARCHAR(16) DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'Type of observation\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', priority SMALLINT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'Priority for menu. Determines the order in the menus list\', UNIQUE INDEX UNIQ_B93BC73EBF396750 (id), INDEX IDX_B93BC73E1023D0F2 (fk_booking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookingPax (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_booking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', title VARCHAR(4) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Title\', name VARCHAR(64) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Name\', surname VARCHAR(64) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Surname\', birthDate DATE DEFAULT NULL COMMENT \'Birth date\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', UNIQUE INDEX UNIQ_D4B48D1ABF396750 (id), INDEX IDX_D4B48D1A1023D0F2 (fk_booking), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookingService (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_booking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_service INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_supplier INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', reference VARCHAR(32) DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'Any reference\', description VARCHAR(256) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Description\', quantity SMALLINT UNSIGNED NOT NULL COMMENT \'Quantity\', startDate DATE NOT NULL COMMENT \'Start date of validation\', endDate DATE NOT NULL COMMENT \'End date of validation\', confirmationStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COLLATE utf8_unicode_ci COMMENT \'Confirmation status\', invoiceStatus VARCHAR(8) DEFAULT \'NO\' NOT NULL COLLATE utf8_unicode_ci COMMENT \'Invoice status\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', isAutoAllot TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Enables auto allot management\', isAutoAvailability TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Enables auto availability management\', totalCost NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total cost value\', totalSell NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total sell value\', totalMargin NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total profit\', UNIQUE INDEX UNIQ_6C897F33BF396750 (id), INDEX IDX_6C897F331023D0F2 (fk_booking), INDEX IDX_6C897F3311B2A7FE (fk_service), INDEX IDX_6C897F33A9022FA0 (fk_supplier), INDEX idx_bookingService_date (startDate, endDate), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookingServicePrice (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', description VARCHAR(256) DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'Description\', postingType VARCHAR(8) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Type of posting\', quantity SMALLINT UNSIGNED NOT NULL COMMENT \'Quantity\', totalSell NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total sell value\', costValue NUMERIC(10, 4) DEFAULT \'0.0000\' NOT NULL COMMENT \'Cost value\', marginMethod VARCHAR(8) DEFAULT NULL COLLATE utf8_unicode_ci COMMENT \'Method to use to determinate the value\', marginValue NUMERIC(10, 4) DEFAULT \'0.0000\' COMMENT \'Margin value\', sellValue NUMERIC(10, 4) DEFAULT \'0.0000\' NOT NULL COMMENT \'Sell value\', userFieldTyped VARCHAR(6) NOT NULL COLLATE utf8_unicode_ci COMMENT \'Field typed by user (COST or SELL)\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_bookingService INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', totalCost NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total cost value\', totalMargin NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total margin\', totalMarkup NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total markup\', totalProfit NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL COMMENT \'Total profit\', UNIQUE INDEX UNIQ_F9787BE5BF396750 (id), INDEX IDX_F9787BE5198796DA (fk_bookingService), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookingTravelService (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT \'Column row identifier\', fk_place INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', insertTime DATETIME NOT NULL COMMENT \'Date and time insertion\', insertUser VARCHAR(32) NOT NULL COLLATE utf8_unicode_ci COMMENT \'User insertion\', isEnabled TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'Determines whether the registry is enabled\', fk_bookingService INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', fk_placeTo INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\', UNIQUE INDEX UNIQ_FE033660BF396750 (id), UNIQUE INDEX UNIQ_FE033660198796DA (fk_bookingService), INDEX IDX_FE033660B5F070B8 (fk_place), INDEX IDX_FE0336603E1A161A (fk_placeTo), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE1AD0877 FOREIGN KEY (fk_user) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE24DA4789 FOREIGN KEY (fk_bookingPax) REFERENCES bookingPax (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE3EBA7B02 FOREIGN KEY (fk_store) REFERENCES store (id)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEE7EA6CC5 FOREIGN KEY (fk_client) REFERENCES client (id)');
        $this->addSql('ALTER TABLE bookingFile ADD CONSTRAINT FK_47A3B9031023D0F2 FOREIGN KEY (fk_booking) REFERENCES booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingObservation ADD CONSTRAINT FK_B93BC73E1023D0F2 FOREIGN KEY (fk_booking) REFERENCES booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingPax ADD CONSTRAINT FK_D4B48D1A1023D0F2 FOREIGN KEY (fk_booking) REFERENCES booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingService ADD CONSTRAINT FK_6C897F331023D0F2 FOREIGN KEY (fk_booking) REFERENCES booking (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingService ADD CONSTRAINT FK_6C897F3311B2A7FE FOREIGN KEY (fk_service) REFERENCES service (id)');
        $this->addSql('ALTER TABLE bookingService ADD CONSTRAINT FK_6C897F33A9022FA0 FOREIGN KEY (fk_supplier) REFERENCES supplier (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookingServicePrice ADD CONSTRAINT FK_F9787BE5198796DA FOREIGN KEY (fk_bookingService) REFERENCES bookingService (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingTravelService ADD CONSTRAINT FK_FE033660198796DA FOREIGN KEY (fk_bookingService) REFERENCES bookingService (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingTravelService ADD CONSTRAINT FK_FE0336603E1A161A FOREIGN KEY (fk_placeTo) REFERENCES place (id)');
        $this->addSql('ALTER TABLE bookingTravelService ADD CONSTRAINT FK_FE033660B5F070B8 FOREIGN KEY (fk_place) REFERENCES place (id)');
        $this->addSql('DROP TABLE travelBookingFile');
        $this->addSql('DROP TABLE serviceBookingFile');
        $this->addSql('DROP TABLE travelBookingObservation');
        $this->addSql('DROP TABLE serviceBookingObservation');
        $this->addSql('DROP TABLE travelBookingPax');
        $this->addSql('DROP TABLE serviceBookingPax');
        $this->addSql('DROP TABLE travelBookingService');
        $this->addSql('DROP TABLE serviceBookingService');
        $this->addSql('DROP TABLE travelBookingServicePrice');
        $this->addSql('DROP TABLE serviceBookingServicePrice');
        $this->addSql('DROP INDEX IDX_E84536F740D39B65 ON serviceBooking');
        $this->addSql('ALTER TABLE serviceBooking CHANGE fk_servicebookingpax fk_bookingPax INT UNSIGNED DEFAULT NULL COMMENT \'Column row identifier\'');
        $this->addSql('ALTER TABLE serviceBooking ADD CONSTRAINT FK_E84536F724DA4789 FOREIGN KEY (fk_bookingPax) REFERENCES bookingPax (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX IDX_E84536F724DA4789 ON serviceBooking (fk_bookingPax)');
        $this->addSql('DROP INDEX IDX_F42889FF86C38CDC ON travelBooking');
        $this->addSql('DROP INDEX IDX_F42889FF3EBA7B02 ON travelBooking');
        $this->addSql('DROP INDEX IDX_F42889FF1AD0877 ON travelBooking');
        $this->addSql('DROP INDEX IDX_F42889FFE7EA6CC5 ON travelBooking');
        $this->addSql('ALTER TABLE travelBooking ADD fk_booking INT UNSIGNED NOT NULL COMMENT \'Column row identifier\', DROP fk_store, DROP fk_user, DROP fk_client, DROP startDate, DROP endDate, DROP invoiceStatus, DROP confirmationStatus, DROP totalCost, DROP totalMargin, DROP totalMarkup, DROP totalProfit, DROP totalSell, DROP fk_travelBookingPax');
        $this->addSql('ALTER TABLE travelBooking ADD CONSTRAINT FK_F42889FF1023D0F2 FOREIGN KEY (fk_booking) REFERENCES booking (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F42889FF1023D0F2 ON travelBooking (fk_booking)');
    }
}
