# src/CommonBundle/Resources/config/services.yml
services:
    common.service.repository:
        class: CommonBundle\Service\RepositoryService
        arguments: ["@doctrine.orm.local_database_entity_manager"]