<?php

namespace BookingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * ServiceBookingServicePriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceBookingServicePriceRepository extends BaseBookingServicePriceRepository
{
    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::processMetadata(array(
            'serviceBookingServiceObj' => array('label' => 'Service Booking Service', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'serviceBookingService', 'bundle' => 'booking', 'type' => 'none')),
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}