<?php

namespace BookingBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;
use AppBundle\Service\HelperService;

/**
 * TravelBookingClientCurrentAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelBookingClientCurrentAccountRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            'travelBookingObj' => array('label' => 'Travel Booking', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'travelBooking', 'bundle' => 'booking', 'type' => 'none')),
            // Separated by steps for wizard
            'clientCurrentAccountObj' => array('label' => 'Client Current Account', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'clientCurrentAccount', 'field' => 'id', 'bundle' => 'accounting', 'type' => 'none',
                    'metadata' => array('method' => 'merge', 'pushAfterField' => 'id')
                ),
                // Form Type Class defined at runtime according with the wizard step number
                // (%formTypeStep% will be correctly replaced)
                'form' => array('type' => 'embed', 'typeClass' => 'ClientCurrentAccountStep%formTypeStep%')
            ),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'none', 'acl' => 'edit', 'default' => true)
        ));
    }

    /**
     * Set invoice status to booking
     * @param $bookingObj
     * @return mixeds
     */
    public function setBookingInvoiceStatus($bookingObj)
    {
        $localTable = $this->getLocalTable();

        // Entities names
        $bookingEntity = HelperService::getClassName($bookingObj);
        $bookingTable = lcfirst($bookingEntity);
        $bookingObjName = ($bookingTable . 'Obj');

        $options = array(
            'fields' => array(
                '(booking.subTotalSell + booking.totalVatSell) AS total',
                // Get the total invoiced.
                // Its used total (value without VAT + VAT, because is more exactly to get original values)
                "(CASE WHEN (clientDocumentType.operation IS NOT NULL) THEN (SUM(CASE WHEN (clientDocumentType.operation = 'DEBIT') "
                . "THEN (clientCurrentAccount.subTotal + clientCurrentAccount.totalVat) "
                . "ELSE ((clientCurrentAccount.subTotal + clientCurrentAccount.totalVat) * -1) END)) ELSE (0) END) AS totalInvoiced"
            ),
            'criteria' => array (
                array(
                    'field' => $bookingObjName,
                    'expr' => 'eq',
                    'value' => $bookingObj->getId()
                ),
                array(
                    'field' => 'isEnabled',
                    'expr' => 'eq',
                    'value' => true
                )
            )
        );

        // Get query builder
        $qb = $this->queryBuilder($options, false);

        // Get booking
        $qb->innerJoin($localTable . "." . $bookingObjName,
            'booking'
        );

        // Get client current account
        $qb->innerJoin($localTable . '.clientCurrentAccountObj',
            'clientCurrentAccount',
            'WITH',
            'clientCurrentAccount.isEnabled = 1'
        );

        // Get document type
        $qb->innerJoin('clientCurrentAccount.clientDocumentTypeObj',
            'clientDocumentType'
        );

        $result = $this->executeQueryBuilder($qb);
        $result = reset($result);

        switch ($result['totalInvoiced']) {
            case 0:
                $bookingObj->setInvoiceStatus("NO");
                break;
            case $result['total']:
                $bookingObj->setInvoiceStatus("YES");
                break;
            default:
                $bookingObj->setInvoiceStatus("PARTIAL");
        }

        return $bookingObj;
    }
}