<?php

namespace BookingBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;
use AppBundle\Service\HelperService;

/**
 * TravelBookingClientCurrentAccountDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravelBookingClientCurrentAccountDetailRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            'travelBookingServicePriceObj' => array('label' => '', 'type' => 'object',
                'acl' => 'read', 'typeDetail' => array(
                    'table' => 'travelBookingServicePrice', 'bundle' => 'booking', 'type' => 'none')
            ),
            'travelBookingServiceObj' => array('table' => 'travelBookingServicePrice', 'label' => '', 'type' => 'object',
                'acl' => 'read', 'dependency' => 'travelBookingServicePriceObj', 'typeDetail' => array(
                    'table' => 'travelBookingService', 'bundle' => 'booking', 'type' => 'none')
            ),
            'bookingService_name' => array('table' => 'travelBookingService', 'field' => 'description', 'label' => '', 'type' => 'text',
                'acl' => 'read', 'dependency' => 'travelBookingServiceObj'),
            'clientCurrentAccountDetailObj' => array('label' => '', 'type' => 'object',
                'acl' => 'read', 'typeDetail' => array(
                    'table' => 'clientCurrentAccountDetail', 'field' => 'id', 'bundle' => 'accounting', 'type' => 'none',
                    'metadata' => array('method' => 'merge', 'pushAfterField' => 'id')
                ),
                'form' => array('type' => 'embed')
            ),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'none', 'acl' => 'edit', 'default' => true)
        ));
    }
}