<?php

namespace CommonBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            // This fields are setted in "newAction"
            /*'context' => array('label' => '', 'type' => 'none', 'acl' => 'edit',
                'form' => array('type' => 'hidden')),
            'contextId' => array('label' => '', 'type' => 'none', 'acl' => 'edit',
                'form' => array('type' => 'hidden')),*/
            'from' => array('label' => 'From', 'type' => 'text', 'acl' => 'edit', 'isDefault' => true),
            'to' => array('label' => 'To', 'type' => 'text', 'acl' => 'edit', 'isDefault' => true),
            'cc' => array('label' => 'CC', 'type' => 'text', 'acl' => 'edit'),
            'bcc' => array('label' => 'BCC', 'type' => 'text', 'acl' => 'edit'),
            'subject' => array('label' => 'Subject', 'type' => 'text', 'acl' => 'edit', 'isDefault' => true),
            'text' => array('label' => 'text', 'type' => 'textarea', 'acl' => 'edit', 'isRequired' => true,
                'attr' => array('rows' => '6')
            ),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read'),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read'),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}