<?php

namespace CommonBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            'countryObj' => array('label' => 'Country', 'type' => 'object', 'acl' => 'edit',
                'typeDetail' => array(
                    'table' => 'country', 'bundle' => 'common', 'type' => 'number', 'fieldInView' => 'country_name'
                ),
                'form' => array('type' => 'auto-complete')
            ),
            'country_name' => array('table' => 'country', 'field' => 'name', 'label' => 'Country', 'type' => 'text',
                'acl' => 'read', 'dependency' => 'countryObj', 'form' => array('type' => 'none')),
            'name' => array('label' => 'Name', 'type' => 'text', 'acl' => 'edit'),
            'type' => array('label' => 'Type', 'type' => 'text', 'acl' => 'edit'),
            'iataCode' => array('label' => 'IATA Code', 'type' => 'text', 'acl' => 'edit'),
            'isoCode' => array('label' => 'ISO Code', 'type' => 'text', 'acl' => 'edit'),
            'icaoCode' => array('label' => 'ICAO Code', 'type' => 'text', 'acl' => 'edit'),
            'latitude' => array('label' => 'Latitude', 'type' => 'text', 'acl' => 'edit'),
            'longitude' => array('label' => 'Longitude', 'type' => 'text', 'acl' => 'edit'),
            'elevation' => array('label' => 'Elevation', 'type' => 'number', 'acl' => 'edit'),
            'timezone' => array('label' => 'Timezone', 'type' => 'text', 'acl' => 'edit'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'none', 'acl' => 'read'),
            'insertUser' => array('label' => 'Insert User', 'type' => 'none', 'acl' => 'read'),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'none', 'acl' => 'read', 'default' => true)
        ));
    }
}