<?php

namespace ServicesBundle\Entity;

use AppBundle\Entity\BasePriceExceptionDefinitionRepository;
use AppBundle\Service\HelperService;

/**
 * ServicePriceExceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicePriceExceptionRepository extends BasePriceExceptionDefinitionRepository
{
    /**
     * Overrides parent
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::$metadata = self::processMetadata(array(
            'serviceObj' => array('label' => 'Service', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'service', 'bundle' => 'services', 'type' => 'none')),
            'description' => array('label' => 'Description', 'type' => 'text', 'acl' => 'edit'),
            'startDate' => array('label' => 'Start Date', 'type' => 'date', 'acl' => 'edit', 'view' => array(
                'typeDetail' => array('rules' => array(array('expr' => 'max', 'value' => 'endDate')))
            )),
            'endDate' => array('label' => 'End Date', 'type' => 'date', 'acl' => 'edit', 'view' => array(
                'typeDetail' => array('rules' => array(array('expr' => 'min', 'value' => 'startDate')))
            ))
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }

    /**
     * Get all objects by date (date inside of interval [startDate, endDate])
     * @param $serviceObj
     * @param $date
     * @param $options (array with queryBuilder options format)
     * @return mixed
     */
    public function getCurrentPriceExceptionByDate($serviceObj, $date, $options = array())
    {
        $options = array_merge_recursive(
            $options,
            array(
                'criteria' => array (
                    array('field' => 'isEnabled', 'expr' => 'eq', 'value' => 1),
                    array('field' => 'serviceObj', 'expr' => 'eq', 'value' => $serviceObj),
                    array('field' => $date, 'expr' => 'rbetween', 'value' => array('startDate', 'endDate'))
                ),
                'orderBy' => array(
                    array('field' => 'insertTime', 'value' => 'DESC')
                )
            )
        );

        return $this->queryBuilder($options);
    }
}