# src/BckCommonBundle/Resources/config/services.yml
services:
    bck.common.service.repository:
        class: Bck\CommonBundle\Service\RepositoryService
        arguments: ["@doctrine.orm.local_database_entity_manager"]