<?php

namespace SysadminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModuleMenuSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleMenuSettingRepository extends EntityRepository
{
}
