<?php

namespace AppBundle\Entity;

/**
 * BasePriceDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
abstract class BasePriceRepository extends BaseEntityRepository
{
    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        return self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            // Field to control how to show the fake field "user_[...]"
            'isVatIncluded' => array('label' => 'VAT included', 'type' => 'none', 'acl' => 'edit', 'default' => true,
                'attr' => array('(change)' => 'onIsVatIncludedChange($event.target.checked)'),
                'form' => array('type' => 'boolean')
            ),
            // Original field is hidden
            'costValue' => array('label' => 'Cost', 'type' => 'monetary', 'acl' => 'edit',
                'form' => array('type' => 'hidden')),
            // Fake field for user type the value (with or without VAT), because the original field is always without VAT
            'user_costValue' => array('label' => 'Cost', 'type' => 'none', 'acl' => 'edit',
                'attr' => array(
                    '(input)' => 'onCostValueEnterKey($event.target.value)',
                    '(focusout)' => 'onCostValueEnterKey($event.target.value)'
                ),
                'form' => array('type' => 'number', 'isMapped' => false),
            ),
            'marginMethod' => array('label' => 'Margin Type', 'type' => 'enum', 'acl' => 'edit', 'isRequired' => false,
                'attr' => array('(change)' => 'onMarginMethodChange($event.target.value)'),
                'typeDetail' => array(
                    'type' => 'text', 'choices' => array(
                        'value' => array(
                            'Margin' => 'MARGIN', 'Markup' => 'MARKUP', 'Fixed' => 'FIXED'
                        )
                    )),
                'form' => array('type' => 'select')
            ),
            'marginValue' => array('label' => 'Margin', 'type' => 'number', 'acl' => 'edit',
                'attr' => array(
                    '(input)' => 'onMarginValueEnterKey($event.target.value)',
                    '(focusout)' => 'onMarginValueEnterKey($event.target.value)'
                )),
            // Original field is hidden
            'sellValue' => array('label' => 'Sell', 'type' => 'number', 'acl' => 'edit',
                'form' => array('type' => 'hidden')),
            // Fake field for user type the value (with or without VAT), because the original field is always without VAT
            'user_sellValue' => array('label' => 'Sell', 'type' => 'none', 'acl' => 'edit',
                'attr' => array(
                    '(input)' => 'onSellValueEnterKey($event.target.value)',
                    '(focusout)' => 'onSellValueEnterKey($event.target.value)'
                ),
                'form' => array('type' => 'number', 'isMapped' => false),
            ),
            'userFieldTyped' => array('label' => '', 'type' => 'hidden', 'acl' => 'edit'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}