<?php

namespace AppBundle\Entity;

/**
 * BasePriceResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePriceResumeRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $localTable = lcfirst(substr(strrchr(get_called_class(), '\\'), 1, -10));

        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            // Disabled to simplify the view and the form
            'subTotalCost' => array('label' => 'Cost (no VAT)', 'type' => 'none', 'acl' => 'read'),
            'subTotalSell' => array('label' => 'Sell (no VAT)', 'type' => 'none', 'acl' => 'read'),
            'totalVatCost' => array('label' => 'Cost VAT', 'type' => 'none', 'acl' => 'read'),
            'totalVatSell' => array('label' => 'Sell VAT', 'type' => 'none', 'acl' => 'read'),
            'totalCost' => array('label' => 'Total Cost', 'type' => 'monetary', 'acl' => 'read',
                'field' => '('.$localTable.'.subTotalCost + '.$localTable.'.totalVatCost)', 'table' => '',
                'attr' => array('readonly' => 'readonly'), 'isRequired' => false,
                'form' => array('type' => 'number', 'isMapped' => false),
                'normalizer' => array('method' => 'getTotalCost')
            ),
            'totalSell' => array('label' => 'Total Sell', 'type' => 'monetary', 'acl' => 'read',
                'field' => '('.$localTable.'.subTotalSell + '.$localTable.'.totalVatSell)', 'table' => '',
                'attr' => array('readonly' => 'readonly'), 'isRequired' => false,
                'form' => array('type' => 'number', 'isMapped' => false),
                'normalizer' => array('method' => 'getTotalSell')
            ),
            'totalMargin' => array('label' => 'Margin (net)', 'type' => 'percentage', 'acl' => 'read'),
            'totalMarkup' => array('label' => 'Markup (net)', 'type' => 'percentage', 'acl' => 'read'),
            'totalProfit' => array('label' => 'Profit (net)', 'type' => 'monetary', 'acl' => 'read'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true)
        ));
    }
}