<?php

namespace AppBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * BasePriceDefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasePriceDefinitionRepository extends BasePriceRepository
{
    /**
     * Overrides parent
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::$metadata = self::processMetadata(array(
            'isVatIncluded' => array('label' => 'VAT included', 'type' => 'boolean', 'acl' => 'edit', 'default' => true)
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}