<?php

namespace Bck\CommonBundle\Entity;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Bck\SysadminBundle\Entity\PlaceRepository {
}