<?php

namespace Bck\ServicesBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * GrouperServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrouperServiceRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) { return self::$metadata; }

        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'serviceObj' => array('label' => '', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'service', 'field' => 'id', 'bundlePrefix' => 'bck', 'bundle' => 'services', 'type' => 'none',
                    'metadata' => array('method' => 'merge', 'persist' => true, 'pushAfterField' => 'id'),
                    'formClass' => 'Bck\ServicesBundle\Form\ServiceNoDetailType'
                ),
                'form' => array('type' => 'embed')
            ),
            // Override fields to be disabled in this entity
            'thumbnail' => array('label' => 'nd', 'type' => 'none', 'acl' => 'read'),
            'isEnabledAvailability' => array('label' => 'nd', 'type' => 'none', 'acl' => 'read'),
            'isEnabledAllot' => array('label' => 'nd', 'type' => 'none', 'acl' => 'read'),
            'isEnabledPrice' => array('label' => 'nd', 'type' => 'none', 'acl' => 'read'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}