<?php

namespace Bck\ServicesBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * PackageServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageServiceRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) { return self::$metadata; }

        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            'serviceObj' => array('label' => '', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'service', 'field' => 'id', 'bundlePrefix' => 'bck', 'bundle' => 'services', 'type' => 'none',
                    'metadata' => array('method' => 'merge', 'persist' => true, 'pushAfterField' => 'id')
                ),
                'form' => array('type' => 'embed')
            ),
            'hasFixedDuration' => array('label' => 'Has Fixed Duration', 'type' => 'boolean', 'acl' => 'edit',
                'default' => false, 'isDefault' => true
            ),
            'fixedDurationDays' => array('label' => 'Duration', 'type' => 'number', 'acl' => 'edit'),
            'hasGroupingServices' => array('label' => 'Has Grouping Services', 'type' => 'boolean', 'acl' => 'edit',
                'default' => false, 'isDefault' => true
            ),
            ////////////////////////////////// MARKETING //////////////////////////////////
            'priceFrom' => array('label' => 'Price From', 'type' => 'monetary', 'acl' => 'edit',
                'isRequired' => false, 'form' => array('type' => 'number'), 'isDefault' => true
            ),
            ///////////////////////////////// EMBED URL //////////////////////////////////
            'embedServiceUrl' => array('label' => 'Embed Service Url', 'type' => 'none', 'acl' => 'read',
                'form' => array('type' => 'text')
            ),
            'embedBookingUrl' => array('label' => 'Embed Booking Url', 'type' => 'none', 'acl' => 'read',
                'form' => array('type' => 'text')
            ),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}