<?php

namespace Bck\AdminBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;
use AppBundle\Service\HelperService;

/**
 * SystemSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemSettingRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $langPrefix = HelperService::getGlobalVar('langPrefix');
        $name_lang = 'name_'.$langPrefix;

        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'none', 'acl' => 'read'),
            'appCountryObj' => array('label' => 'Country', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'app_country', 'bundlePrefix' => 'bck', 'bundle' => 'sysadmin', 'type' => 'none'),
                'form' => array('type' => 'select')
            ),
            'country_name' => array('table' => 'app_country', 'field' => $name_lang, 'label' => 'Country', 'type' => 'text',
                'acl' => 'read', 'dependency' => 'appCountryObj', 'form' => array('type' => 'none'),
                'normalizer' => array('method' => 'getName')
            ),
            'appCurrencyObj' => array('label' => 'Currency', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'app_currency', 'bundlePrefix' => 'bck', 'bundle' => 'sysadmin', 'type' => 'none'),
                'form' => array('type' => 'select')
            ),
            'currency_name' => array('table' => 'app_currency', 'field' => $name_lang, 'label' => 'Currency', 'type' => 'text',
                'acl' => 'read', 'dependency' => 'appCurrencyObj', 'form' => array('type' => 'none'),
                'normalizer' => array('method' => 'getName')
            ),
            'appLanguageObj' => array('label' => 'Language', 'type' => 'object', 'acl' => 'edit', 'typeDetail' => array(
                'table' => 'app_language', 'bundlePrefix' => 'bck', 'bundle' => 'sysadmin', 'type' => 'none'),
                'form' => array('type' => 'select')
            ),
            'language_name' => array('table' => 'app_language', 'field' => $name_lang, 'label' => 'Language', 'type' => 'text',
                'acl' => 'read', 'dependency' => 'appLanguageObj', 'form' => array('type' => 'none'),
                'normalizer' => array('method' => 'getName')
            ),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}