<?php

namespace Bck\AccountingBundle\Entity;

use AppBundle\Entity\BaseEntityRepository;

/**
 * PaymentMethodDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentMethodDetailRepository extends BaseEntityRepository
{
    static protected $metadata = null;

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get local metadata (it needs to be implemented by children to get static variable with local metadata from parent)
     * @return mixed
     */
    protected function getLocalMetadata()
    {
        return $this->getMetadata();
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }
        return self::$metadata = self::processMetadata(array(
            'id' => array('label' => 'Id', 'type' => 'number', 'acl' => 'read'),
            'paymentMethodObj' => array('label' => 'Payment Method', 'type' => 'object', 'acl' => 'read', 'typeDetail' => array(
                'table' => 'paymentObject', 'bundlePrefix' => 'bck', 'bundle' => 'accounting', 'type' => 'none')),
            'appPaymentMethodDetailObj' => array('label' => '', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array(
                    'table' => 'app_paymentMethodDetail', 'field' => 'id', 'bundlePrefix' => 'bck', 'bundle' => 'sysadmin', 'type' => 'none'
                )
            ),
            'field' => array('table' => 'app_paymentMethodDetail', 'field' => 'field', 'label' => '',
                'type' => 'none', 'acl' => 'read', 'dependency' => 'appPaymentMethodDetailObj'),
            'type' => array('table' => 'app_paymentMethodDetail', 'field' => 'type', 'label' => '',
                'type' => 'none', 'acl' => 'read', 'dependency' => 'appPaymentMethodDetailObj'),
            'options' => array('table' => 'app_paymentMethodDetail', 'field' => 'options', 'label' => '',
                'type' => 'none', 'acl' => 'read', 'dependency' => 'appPaymentMethodDetailObj',
                'normalizer' => array('method' => 'getNormalizedOptions')
            ),
            'label' => array('table' => 'app_paymentMethodDetail', 'field' => 'label', 'label' => 'Name',
                'type' => 'text', 'acl' => 'read', 'dependency' => 'appPaymentMethodDetailObj'),
            'value' => array('label' => 'Value', 'type' => 'text', 'acl' => 'edit'),
            'insertTime' => array('label' => 'Insert Time', 'type' => 'datetime', 'acl' => 'read', 'form' => array('type' => 'none')),
            'insertUser' => array('label' => 'Insert User', 'type' => 'text', 'acl' => 'read', 'form' => array('type' => 'none')),
            'isEnabled' => array('label' => 'Enabled', 'type' => 'boolean', 'acl' => 'edit', 'default' => true,
                'view' => array('keepOriginalNormalizer' => true)
            )
        ));
    }
}