<?php

namespace Bck\AccountingBundle\Entity;

use AppBundle\Service\HelperService;

/**
 * SupplierDocumentReceiptPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierDocumentReceiptPaymentRepository extends BaseDocumentReceiptPaymentRepository
{
    static protected $metadata = null;

    /**
     * Defines parent method
     * @return string
     */
    protected function getLocalEntityContext()
    {
        return 'supplier';
    }

    /**
     * Get field metadata
     * @param $field
     * @param $attribute
     * @param $metadata (uses this metadata instead of local metadata)
     * @param $context ('view'|'form'|'none')
     * @return null
     */
    static public function getFieldMetadata($field, $attribute, $metadata = null, $context = 'none')
    {
        if (!$metadata) {
            $metadata = self::getMetadata();
        }
        return self::getLocalFieldMetadata($field, $attribute, $metadata, $context);
    }

    /**
     * Get entity metadata
     * @return mixed
     */
    static function getMetadata()
    {
        // Process metadata only once
        if (self::$metadata) {
            return self::$metadata;
        }

        $parentMetadata = parent::getMetadata();

        $localMetadata = self::processMetadata(array(
            'supplierDocumentObj' => array('label' => 'Supplier Current Account', 'type' => 'object', 'acl' => 'read',
                'typeDetail' => array('table' => 'supplierDocument', 'bundlePrefix' => 'bck', 'bundle' => 'accounting', 'type' => 'none'))
        ));

        return self::$metadata = HelperService::pushIntoArray($parentMetadata, $localMetadata, 'id');
    }
}